_start notes_

Today is: _2025.07.22_
This is a list of: _Files that run without breaking_

_1_cluster.Rmd_ (ends at line 895)
  - Table: mean species percent cover x cluster
  - (Figure: NMDS of cluster indicator spp and NMDS sig spp x cluster (object: grid.arrange(nmds_nat, ...)))


_1.1_transect_continuous.Rmd_ (ends @ line 2916)
  - Figure: total shrub cover x nngrass cover (object: nngxnatshr, around line 1197)
  - Figure: sage scrub shrub cover x nngrass cover (object: nngxss, around line 1382)
  - Figure 1: 
  - Figure: mean percent cover x cluster (object: fig_forbgrass) ---  mean percent cover (%) x lifeform_lifecycle_status x cluster 
  - Figure: ground type cover (%) x nngrass (obect: fig_bareground_all, around like 1850)
    
  - Figure: Shrub density Median +/- SD x Cluster and Lifestage  (object: densitymeans_bycluster_figure)
  - Figure: stand height x transect (object: fig_height, around line: 2441)
      - median (Q1-Q3): height x cluster
      
  - Figure: COV x transect (object: fig_cov, around: line 2551)
      - mean + SE: COV x cluster
      
  - Figure: shrub density (mature, immature, seedling, dead) x nn grass cover (object: fig_den_mature, around line 2854)
  - Table: Shrub density Median +/- SD x Cluster and Lifestage (object: densitymeans_bycluster_TABLE)
  
  - percent cover by species per transect (around line: 676) (object: abcover_omitground %>% group_by(site_rep, species)...)


_1_july2025.Rmd_
  - Figure: NMDS of cluster analysis indicator species x cluster (object: grid.arrange(nmds_nat, ...) 

_1_spprich.Rmd_ (ends @ line 403)
  - species richness (df: spprich) - number of species, genera, families, native, non-native 
  - Figure: species richness by transect x nngrass cover (obect: plot_spprich, around like 517)
  - Figure: species richness by status x nngrass cover (obect: plot_spprich_native, around like 535)
  - Figure: species richness by lifeform x nngrass cover (obect: plot_spprich_shrub, around like 578)
  

1.3_NMDS_percentcover.Rmd (ends @ line 614)


density_cover
_2_envrion_NMDS.Rmd_ (ends @ line 1323)
  - Table: Summary of Environmental Variables by Plant Cluser (obejct: table_plant)

2.2_visualize_environdata.Rmd (ends @ line 368)

_3_seedbank_clusterNMDSdiversity.Rmd_ (start: # 2025 by plant cluser; ends @ line 1428)
  - Table: Median Average Germination x species x Seedbank Cluster (object: table_germ)
  - species richness (~line 1439); df = seedbankgerm_plantcluster_summary
  - Figure: seedbank NMDS x seedbank cluster (object: grid.arrange(seed.nmds_nat, ... )

COV - there's code to calculate COV in ab_heightdensity.Rmd, but I would need to edit the code to include all 40 transects. 

_Files no longer in use:_
1.2_twinspan.Rmd <-- I'm not running TWINSPAN analysis. Plus, I can't run the program on a Mac.
2.1_transect_compile_environdata.Rmd <- these are the flowcharts
2.3_PCA.Rmd <-- Don't run this code for PCAs. Run NMDSs instead. - SML (june 7, 2025)

ab_percentcover.Rmd <- i think this is an old .Rmd. I'm still using STANDTYPE, and the transect list isn't complete - specifically, df: abcover_vegcover_long_vegonly includes 14 transects at Site 1, five transects at INT, BUT only 1 transects at SIte 2. <-- I would need to add CLUSTER names (df: my_groups) to run by cluster name instead of by STANDTYPE or to add standtype data in a new column.

ab_heightdensity.Rmd <- I think this is an old file too. The standstypes are DEG1, DEG2, ENH1, ENH2, INT1, INT2, INT3, which reflect the old data before I collected more tansect data (transects should be n = 40).


_Useful code to hang on to:_

#### _save_ figure
# ggsave("Ch1_Degradation_figures/nmds_above_vectors.png", nmdsabove_plot_site_rep, width = 8, height = 6)

# Add _labels to the plots_ using cowplot's draw_label() function
fig.1a_labeled <- ggdraw(fig.1a) + draw_label("C", x = 0.95, y = 0.92, size = 15)  # Add letter "A" in the top-right corner

# _Combine the plots_ in a 2x3 layout
figure1 <- plot_grid(fig.1f_labeled, fig.1a_labeled, 
             fig.1d_labeled, fig.1c_labeled,  NULL, fig.1e_labeled,
             nrow = 3, 
             ncol = 2, 
             widths = c(1, 1), # Custom widths for each column
             heights = c(1, 1, 1) # Custom heights for each row
             ) 
             
             
             
(7) NMDS by site (e.g., Intact_1) <-- from 1.3_NMDS_percentcover.Rmd ~line 1102 (code from KIT)
```{r transpose site percent cover data, eval = FALSE}

# pivot wider to create a matrix of percent cover by species by transect (n = 40)
abcover_bysite_nmdsprep <- abcover_byspecies %>% 
  tidyr::spread(site_rep, percentcover) %>% # transpose data so columns are site_rep
  replace(is.na(.), 0) # replace NA with zeros
view(abcover_bysite_nmdsprep)

abcover_bysite_nmdsprep_num <- abcover_bysite_nmdsprep %>% 
  # use the ungroup() function to take out grouping
  ungroup() %>% 
  select(!c(standtype, site, species, status, lifeform, lifecycle, count_per_dist))
         
view(abcover_bysite_nmdsprep_num) # only numbers
```

_end notes_


abcover_fulljoin %>% group_by(site) %>% length(unique(transect))

(1) How does community composition (e.g., percent cover by lifeform, shrub recruitment) and structure (e.g., canopy height) change across a shrub-grass recovery gradient?, (2) How many community-types can be identified across a shrub-grass ‘recovery’ gradient and which species define each community-type?Can transitional plant groupings be identified between shrub-dominated and grass-dominated communities and, if so, which species define these groupings?, (3) How do environmental variables (i.e., slope, aspect, southwestness, total solar radiation, recent fire history) differ among community-types?, and (4) How do seedbank communities along a shrub-grass recovery gradient compare in terms of native species richness and composition?


spplist_0_dataprep <- sppchar %>%
  filter(!species %in% c("wood", "litter", "rock", "moss")) %>%
  distinct(species) %>%
  arrange(species)

spplist_1.1_transect_continuous <- specieslist %>%
 # filter(!species %in% c("wood", "litter", "rock", "moss")) %>%
  distinct(species) %>%
  arrange(species)


sort(unique(specieslist$species))
