---
title: "Using twinspan to identify communities among chaparral transects"
author: "Kit Swift"
date: "2024-06-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libraries
```{r}
# devtools::install_github("jarioksa/twinspan") # if not installed yet

# MS Windows
# https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html # You may need rtools updated 

# MacOS: install C and Fortran compiler
# in terminal, install Homebrew, which installs 'gcc' and includes a 'gfortran' compiler --> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# in terminal, install brew install GCC (which includes gfortran): brew install gcc

#install.packages("twinspan", repos = "https://jarioksa.github.io/drat/")
#
library(tidyverse)
library(twinspan)
library(vegan) # for data 
```

# Percent cover   
```{r load data}

# data were processed and csv's were created in 1_NMDS_percentcover.Rmd

data <- read.csv("processed/twinspan_withdeadspecies.csv", header = TRUE) %>% # df contains percent cover by unique dead and alive species (e.g., "Heteromeles arbutifolia dead" and "Heteromeles arbutifolia") and percent cover by unique Bromus species when they could be identified to species (e.g., "Bromus rubens", "Bromus diandrus", and "Bromus spp.")
   dplyr::select(!c(X, site))

#turning the sites into the row names (for easy reference later)
rownames(data) <- data[,1]
data[,1] <- NULL

data_simplified <- read.csv("processed/twinspan_species.csv", header = TRUE) %>%  # transect "hits" of dead species were renamed as alive (e.g., "Heteromeles arbutifolia dead" ~ "Heteromeles arbutifolia") and all Bromus species were combined into "Bromus spp." (e.g., Bromus diandrus, Bromus rubens, and Bromus hordeaceous ~ "Bromus spp."). Percent cover was then calculated by species. 
   dplyr::select(!c(X, site))

#turning the sites into the row names (for easy reference later)
rownames(data_simplified) <- data_simplified[,1]
data_simplified[,1] <- NULL
data_simplified[,51] <- NULL


```

```{r regular Twinspan}

tw_data <- twinspan(data)
summary(tw_data)

nodePar <- list(lab.cex = 0.4, pch = c(NA, 19), 
                cex = 0.4, col = "green3")

plot(as.dendrogram(tw_data, "species"), type = "rectangle", nodePar = nodePar) #creates a dendogram based on species 
plot(as.dendrogram(tw_data, "quadrat"), type = "rectangle", nodePar = nodePar) #creates a dendogram based on the sample

plot(as.hclust(tw_data, "species")) #creates a Hierarchical Cluster Tree based on the species
plot(as.hclust(tw_data, "quadrat")) #creates a Hierarchical Cluster Tree based on the sample

twintable(tw_data) #the table of relatedness, 00 is closer to 01 than it is to 11 and vice versa 
image(tw_data)

misclassified(tw_data) #none~
```

```{r simple Twinspan}

tw_data_simplified <- twinspan(data_simplified)
summary(tw_data_simplified)
plot(as.dendrogram(tw_data_simplified, "species"), type = "rectangle", nodePar = nodePar) #creates a dendogram based on species 
plot(as.dendrogram(tw_data_simplified, "quadrat"), type = "rectangle", nodePar = nodePar) #creates a dendogram based on the sample

plot(as.hclust(tw_data_simplified, "species")) #creates a Hierarchical Cluster Tree based on the species
plot(as.hclust(tw_data_simplified, "quadrat")) #creates a Hierarchical Cluster Tree based on the sample

twintable(tw_data_simplified) #the table of relatedness, 00 is closer to 01 than it is to 11 and vice versa 
image(tw_data_simplified)

misclassified(tw_data_simplified) #none~
```


```{r Twinspan proper}
#twinspan

data(dune) #from vegan, other options include: varespec, mite, sipoo

tw <- twinspan(x = varespec #,
               #cutlevels = c(0, 2, 5, 10, 20), #these are the default cut levels
               #indmax = 7, #the maximum number of indidcators for each division (<= 15)
               #groupmax = 5, #the minimum group size for division (>= 2)
               #levmax = 6, #maximum levels of depth (<= 15), how many times itll divide
               #lind, #whether or not you want certain psuedospecies levels to be considered in the indidcator analysis
               #lwgt, #weights for species levels
               #noind #any species you do NOT want to be indicators for some reason
               )

summary(tw) #this gets us the eigenvalues of each correspondance analysis, and the indidcator pseudospecies

plot(as.dendrogram(tw, "species"), type = "triangle") #creates a dendogram based on species 
plot(as.dendrogram(tw, "quadrat"), type = "triangle") #creates a dendogram based on the sample

plot(as.hclust(tw, "species")) #creates a Hierarchical Cluster Tree based on the species
plot(as.hclust(tw, "quadrat")) #creates a Hierarchical Cluster Tree based on the sample

twintable(tw) #the table of relatedness, 00 is closer to 01 than it is to 11 and vice versa 
image(tw) #a heatmap of the groups

# almost all of these represent the same data, so its likely youll only need the dendograms and hclusters 

# cut(tw) #returns vector of twinspan classes at a given level of hierarchy or classes respecting group heterogeneity for quadrats or species. 
# eigenvals(tw) #returns the eigenvalues of twinspan divisions. I do not know what the eigenvalues tell us
```

```{r}
# This is the error checking thing I mentioned
# From documentation: twinspan bases its quadrat classification primarily on ordination axis. In some cases this is in conflict with the classification derived from indicator pseudospecies. This function identifies these cases. 
# Twinspan is not an indicator species analysis, it is a dichotomized ordination analysis that also does a basic indicator species analysis
# It takes into account the indicator species analysis when it builds its groups, but it can build the groups differently than what the indicator species may imply
# this function finds those differences. If there are a lot, it may be worth it to look into modern "indicator species analysis" (IDA), if there are few to none, you dont have to worry about it :)
misclassified(tw) 
# (the dune and sipoo datasets give me no misclassifications, so its likely itll be fine)
```

# Seedbank

```{r}
# the original .csv is located here:
# seedbank_load_raw <- read.csv("deg_seedbank_20231007.csv", header = TRUE, na.strings=c("","NA"))

seedbank <- read.csv("processed/seedbank_NMDS_202401.csv", header = TRUE) %>% 
   dplyr::select(!c(X, stand))

```