---
title: "2.3_DCCA"
author: "Stephanie Ma Lucero"
date: "2024-08-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://www.davidzeleny.net/anadat-r/doku.php/en:pca_examplesv

```{r load data}


extracted_load <- read.csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022/chaparraldegradation_2022/Extracted_Elevation_Slope_Aspect_Hillshade_20m.csv", header = TRUE, na.strings=c("","NA")) 

extracted <- extracted_load%>% 
  dplyr::select(!c(system.index, ID, .geo)) %>% 
  rename(transect_ID = system_ind, 
         aspect_degrees = aspect, 
         elevation_m = elevation, 
         slope_degrees = slope
         ) %>% 
# “southwest-ness” is calculated using: cos (aspect - 225°)
      mutate(transect_ID = case_when(transect_ID == "1.1" ~ "1.10", # old ~ new
                                   transect_ID == "2.1" ~ "2.10",
                                   transect_ID == "2.2" ~ "2.20",
                                   TRUE ~ transect_ID)) %>% 
  
   mutate(
      aspect_degrees = as.numeric(aspect_degrees),
      elevation_m = as.integer(elevation_m),
      slope_degrees = as.numeric(slope_degrees),
      group_15 = as.character(group_15),
      group_9 = as.character(group_9),
      group_6 = as.character(group_6),
      group_4 = as.character(group_4),
      group_2 = as.character(group_2),
      transect_ID = as.character(transect_ID), 
      fire_history = as.integer(fire_history), 
      twi = as.numeric(twi)
      )
  
# view(extracted)

```

```{r chatgpt code for CCA}
# Load necessary library
library(vegan)

# Assuming species_data is your species composition dataframe
# and env_data is your environmental variables dataframe

# Perform CCA
cca_result <- cca(species_data ~ slope + southwestness + elevation + TWI + solar_radiation, data = varespec)

# Detrending CCA results (the function 'cca' includes a method for DCCA)
dcca_result <- decorana(cca_result)

# View the results
summary(dcca_result)

# Plot the results
plot(dcca_result)


```