---
title: "ab species richness"
author: "Stephanie Ma Lucero"
date: "2024-02-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r above ground - species richness - native richness, include = FALSE}

### SPECIES RICHNESS DATA IS IN CH1_DEGRADATION_ABCOVERNMDS.RMD FILE ###






# species richness, native richness
abrich_full <- read.csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022b/deg_abrich.csv", header = TRUE, na.strings=c("","NA")) %>% 
  dplyr::select('trasecttype', 'standtype', 'site', 'rep', 'distance', 'vertical', 'species', 'lifeform', 'status', 'lifecycle', 'Family', 'lifestage') %>% 
  rename(transecttype = trasecttype, 
         family = Family)
glimpse(abrich_full)

# native shrub density 
shrubdensitylife_full <- read_csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022b/deg_beltdensity_bylifestage.csv", 
    col_types = cols(
      StandType = col_character(), 
      Site = col_character(),
      rep = col_integer(),
      ScientificName = col_character(), 
      dead = col_integer(),
      immature = col_integer(),
      mature = col_integer(), 
      resprout = col_integer(), 
      seedling = col_integer()
      )
     ) %>% 
  rename()
  


shrubdensityspp_full <- read_csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022b/deg_beltdensity_byspecies.csv")
# shrubdensityalive_full <- read_csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/deg_beltdensity_seperatealive.csv")

```
