---
title: "ChapDegNMDS"
author: "Kit Swift"
date: "2023-12-19"
output: pdf_document
---
```{r R citation}
R.Version() # R
RStudio.Version() # RStudio
```


```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#the libraries
library(here) # similar to set working directory
library(tidyverse)
library(gridExtra)
library(ggthemes)
library(plotly)
library(ggpubr)
library(vegan)
library(readxl) 
library(multcompView) 
library(ggpmisc)
library(segmented)
library(ggvegan)
```


```{r Data in}
#any outside data is pulled in here

germination_raw <- read_xlsx("processed/germination_m2.xlsx")
density_raw <- read_csv("processed/shrubdensity.csv")
abcover_raw <- read_csv("processed/abcover_full_omitground.csv")


```


```{r Unified data frame}
sort(unique(abcover_raw$species))
abcover_byspecies <- abcover_raw %>% 
  mutate(species = case_when(species == "Bromus madritensis" ~ "Bromus spp.", # old name ~ new name
                                species == "Bromus rubens" ~ "Bromus spp.",
                             species == "Bromus rubens dead" ~ "Bromus spp.",
                               species ==  "Bromus diandrus" ~ "Bromus spp.",
                             species ==  "Bromus diandrus dead" ~ "Bromus spp.",
                                 species == "Bromus hordeaceus" ~ "Bromus spp.", 
                                species == "Bromus spp. dead" ~ "Bromus spp.", 
                              species == "Avena barbata dead" ~ "Avena barbata", 
                                   species == "Centaurea melitensis dead" ~ "Centaurea melitensis",
                              species == "Erodium cicutarium" ~ "Erodium spp.",
                                 species == "Hirschfeldia incana dead" ~ "Hirschfeldia incana",
                             TRUE ~ species)) %>%
   #                            species ==  "Bromus diandrus dead" ~ "Brom)
   # mutate(species = case_when(species == "Bromus diandrus" ~ "Bromus spp.", # old name ~ new name
   #                            species ==  "Bromus diandrus dead" ~ "Bromus spp. dead",
   #                              species == "Bromus hordeaceus" ~ "Bromus spp.",
   #                            species == "Bromus madritensis" ~ "Bromus spp.",
   #                              species == "Bromus rubens" ~ "Bromus spp.",
   #                            species == "Bromus rubens dead" ~ "Bromus spp. dead",
   #                             species == "Bromus hordeaceus" ~ "Bromus spp.",
   #                      
   #                            species == "Hirschfeldia incana dead" ~ "Hirschfeldia incana",
   #        TRUE ~ species)) %>%
  group_by(site, species, lifeform, status, family) %>% 
  filter(site_rep != "Intact4_4") %>% #omit Intact 4 from data
  filter(!is.na(species)) %>% # omit blank cells in species 
  dplyr::summarize(
    count_per_dist = n_distinct(site_rep_dist), 
    percentcover = n_distinct(site_rep_dist)/41) %>% 
  ungroup() %>%
  dplyr::select(c(site, species, percentcover)) %>% 
  mutate(datatype = as.character("ab")) %>% # adding "percent cover" identifier to species name
  mutate(species_datatype = paste(species, datatype, sep="_")) %>% 
  dplyr::select(!c(species, datatype)) %>% 
  rename(species = species_datatype)

density_byspecies <- density_raw %>%  
  mutate(species_lifestage = paste(species, status, sep="_")) %>% 
    mutate(datatype = as.character("dn")) %>% # adding "density" identifier to species_lifeform name
  mutate(species_lifestage_datatype = paste(species_lifestage, datatype, sep="_")) %>% 
    group_by(site, rep, site_rep, species, status, species_lifestage_datatype) %>% 
   dplyr::summarize(density_100m2 = (((sum(count))/80)*100)) %>% 
  group_by(site, species_lifestage_datatype) %>% 
   dplyr::summarize(mean_density_100m2 = mean(density_100m2)) %>% 
  rename(species = species_lifestage_datatype)

densitycountbytransect <- density_raw %>%   
  group_by(site, rep, site_rep, species, status) %>% 
  dplyr::summarize(density_80m2 = sum(count)) 
  

sort(unique(germination_raw$species_diversity))
germination_byspecies <- germination_raw %>%
  group_by(site, species_diversity) %>%
  mutate(species_diversity = case_when(
    species_diversity == "Bromus diandrus" ~ "Bromus spp.", # old name ~ new name
    species_diversity == "Bromus hordeaceus" ~ "Bromus spp.",
    species_diversity == "Bromus madritensis" ~ "Bromus spp.",
    species_diversity == "Erodium cicutarium" ~ "Erodium spp.",
     species_diversity == "Erodium moschatum" ~ "Erodium spp.",
         species_diversity == "Phacelia tanacetifolia" ~ "Phacelia spp.",
     species_diversity == "Phacelia viscida" ~ "Phacelia spp.",
                              TRUE ~ species_diversity)) %>%
  rename(species = species_diversity) %>%
  dplyr::summarize(seed_density = mean(n_per_g)) %>% 
  mutate(datatype = as.character("sd")) %>% # adding "seed bank" identifier to species name
  mutate(species_datatype = paste(species, datatype, sep="_")) %>% 
  dplyr::select(!c(species, datatype)) %>% 
  rename(species = species_datatype)

abcover_nmdsprep <- abcover_byspecies %>%
  tidyr::spread(species, percentcover) %>% 
  replace(is.na(.), 0)

density_nmdsprep <- density_byspecies %>%
  tidyr::spread(species, mean_density_100m2) %>%
  replace(is.na(.), 0) %>% 
  mutate(site = case_when(
    site == "Intact1" ~ "INT1", 
     site == "Intact2" ~ "INT2", 
     site == "Intact3" ~ "INT3", 
     TRUE ~ site))

germination_nmdsprep <- germination_byspecies %>%
  tidyr::spread(species, seed_density) %>% 
  replace(is.na(.), 0)

nmds_total_prep <- abcover_nmdsprep %>%
  left_join(density_nmdsprep, by = "site") %>%
  left_join(germination_nmdsprep, by = "site") %>% 
  replace(is.na(.), 0) 

nmds_total <- nmds_total_prep %>%
  dplyr::select(!c("site"))
```

```{r NMDS Prep}


nmds_total.hel <- decostand(nmds_total, method = "hellinger")

nmds_total.nmds <- metaMDS(nmds_total, 
                 autotransform = T,
                 distance = "bray",
                 k = 2,
                 try = 100,
                 trymax = 100)

stressplot(nmds_total.nmds)
plot(nmds_total.nmds)

ordiplot(nmds_total.nmds, type = "p")


nmds.fort <- fortify(nmds_total.nmds)
```

```{r NMDS prep from Stephanie code}

nmds_total.nmds2 <- metaMDS(nmds_total, 
                            autotransform = T,
                             distance = "bray", # raup, bray
                 k = 2,
                 try = 100,
                 trymax = 100)

scores(nmds_total.nmds2)

stressplot(nmds_total.nmds2)
plot(nmds_total.nmds2)

nmds2.fort <- fortify(nmds_total.nmds2)
#write.csv(nmds2.fort, "Ch1_Degradation_figures/nmds2.fort.csv")

ordiplot(nmds_total.nmds2, type = "p") # run together 
orditorp(nmds_total.nmds2,display="sites",cex=1.25,air=0.01) # sites aka. hillslopes
orditorp(nmds_total.nmds2,display="species",col="red",air=0.01) # species 


nmds2_df <- data.frame(nmds_total.nmds2$points, nmds_total_prep) # adds NMDS1 and NMDS2 values

# plot: nmds x hillslopes
colnames(nmds2_df)[colnames(nmds2_df) == 'site'] <- 'hillslope' # rename "site" to "hillslope"

total_nmds2_hillslope <- ggplot(nmds2_df, 
       aes(x = MDS1, y = MDS2, color = hillslope, shape = hillslope)) + # shape = site, color = site
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("orange", "brown", "green", "darkgreen", "lightblue", "blue", "navy")) + #"gray0", "gray30", "gray60"
  scale_shape_manual(values = c(16,16, 15, 15, 17, 17, 17)) + 
  theme_bw() +
  #stat_ellipse(linetype = 2, size = 1) +
  labs(title = "NMDS: all data")

# adding vectors to the dataframe
nmds_total_prep <- nmds_total_prep %>% 
  mutate(standtype_ID = 1)
nmds_total_prep$standtype_ID <- 1:7 #shorten df to first 7 rows

nmds_total.nmds2_plot <- scores(nmds_total.nmds2, display = "sites") %>% 
  as.data.frame() %>% 
  rownames_to_column("standtype_ID") %>% 
  mutate_at(c('standtype_ID'), as.numeric) %>% 
  full_join(nmds_total_prep, by = "standtype_ID") %>%  
  dplyr::select(!c(standtype_ID)) 

dim(nmds_total.nmds2_plot)

# extracting pvalues
nmds_total.nmds2_fit <- envfit(nmds_total.nmds2, # envfit() takes the output of metaMDS() and the species matrix you created
                          nmds_total_prep, perm = 999) # pvalues for spp and stand, site, stand_core

nmds_total.nmds2_pvals <- nmds_total.nmds2_fit$vectors$pvals %>% 
  as.data.frame() %>% 
  rownames_to_column("species") %>% 
  dplyr::rename("pvals" = ".") %>% 
  filter(!species == 'standtype_ID')
nmds_total.nmds2_pvals.fort <- fortify(nmds_total.nmds2_pvals)
#write.csv(nmds_total.nmds2_pvals.fort,"Ch1_Degradation_figures/nmds2_pvals.csv")

# extracting coordinates for hillslopes
nmds_total.nmds2_coord <- nmds_total.nmds2_fit %>% 
  scores(., display = "vectors") %>% 
  as.data.frame() %>% 
  rownames_to_column("species") %>% 
  full_join(., nmds_total.nmds2_pvals, by = "species") %>% 
  filter(pvals <= 0.05) %>% # <-- set p-value level here: 0.05, 0.008
  filter(!species == 'standtype_ID')
dim(nmds_total.nmds2_coord) # <-- limit number of vectors to <7 for clarity
#write.csv(nmds_total.nmds2_coord,"Ch1_Degradation_figures/nmds2_pval.1.csv")

# plot: nmds x hillslopes + labels 
total_nmds2_hillslope_vectors <- ggplot(nmds_total.nmds2_plot %>% # output of scores()
                                          rename(hillslope = site), 
                                   aes(x = NMDS1, y = NMDS2)) +
  coord_cartesian(xlim = c(-1.6, 1.6), ylim = c(-1.6, 1.6)) +
   scale_x_continuous(breaks = seq(-1.6, 1.6, by = 0.4)) +  # Add tick marks 
   scale_y_continuous(breaks = seq(-1.6, 1.6, by = 0.4)) +   # Add tick marks
  geom_point(aes(color = hillslope, shape = hillslope), 
             size = 3, alpha = 0.8, position = position_jitter(width = 0.05, height = 0.05)) + # hillslope point jitter
  #stat_ellipse(aes(color = hillslope)) +
 scale_color_manual(values = c("orange", "brown", "green", "darkgreen", "lightblue", "cornflowerblue", "blue")) + #"gray0",
   scale_shape_manual(values = c(16,16, 15, 15, 17, 17, 17)) + 
  theme_bw() +
  geom_segment(data = nmds_total.nmds2_coord, aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")),
                col = "black") +
   geom_text(data = nmds_total.nmds2_coord, 
             aes(label = species),  
             position = position_jitter(width = 0.2, height = 0.2), # spp label jitter
             size = 3) + # Adjust font size for vector labels
  labs(x = "NMDS1", y = "NMDS2", title = "Community composition by hillslope percent cover, shrub density, seed density") +
 theme(axis.text.x = element_text(size = 10),  # Adjust font size for x-axis labels
        axis.text.y = element_text(size = 10),  # Adjust font size for y-axis labels
        axis.title = element_text(size = 12),   # Adjust font size for axis titles
        plot.title = element_text(size = 14))   # Adjust font size for plot title

total_nmds2_hillslope_vectors 
total_nmds2_hillslope_vectors + theme_bw()
total_nmds2_hillslope_vectors + theme_bw()
total_nmds2_hillslope_vectors + theme_bw()
total_nmds2_hillslope_vectors + theme_bw()
total_nmds2_hillslope_vectors + theme_bw()
total_nmds2_hillslope_vectors + theme_bw()
total_nmds2_hillslope_vectors + theme_bw()

ggsave("Ch1_Degradation_figures/nmds_all.png", total_nmds2_hillslope_vectors, width = 8, height = 6)
```

```{r NMDS Graphing}

duneplot <- ggplot() + 
  
  #putting all the "site" data on the graph, these are the different observations
  geom_point(data = subset(nmds.fort, score == 'sites'),
             mapping = aes(x = NMDS1, y = NMDS2),
             alpha = 0.5,  #transparency (to hide/show)
             color = "darkorange",
             show.legend = F) +
  
  #while this is the species data, or abundance based on different observations. 
  geom_point(data = subset(nmds.fort, score == 'species'), 
             mapping = aes(x = NMDS1, y = NMDS2),
             alpha = 0.5, #transparency (to hide/show)
             color = "blue",
             show.legend = F) 

duneplot





```

