---
title: "ch1_standdeg_seedbank"
author: "Stephanie Ma Lucero"
date: "2023-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install libraries, include=TRUE}
library(here) # similar to set working directory
library(tidyverse) # data wrangling - includes ggplot2, dplyr, tidyr, readr, purr, tibble, stringr, forcats
library(ggplot2) # data visualization
library(dplyr)
library(ggthemes)
library(plotly)
library(ggpubr) # customize ggplot2 for publication
library(vegan) #community ecology package - includes, MASS, cluster, mgcv
library(readxl) # for .xls and .xlsx sheets
library(multcompView) #Visualizations of Paired Comparisons, functions: TukeyHSD, dist{stats}, simint, simtest, csimint, csimtest{multcomp}, friedmanmc, kruskalmc{pgirmess}
```

# Load data

```{r load seedbank data, include=TRUE}

# STAND COMPARISONS BY SEEDBANK SPECIES RICHNESS AND GERMINATION COUNTS - OMIT Zeros
# 1. species richness - use "species_richness" column 
# 2. native species richness - filter status == "native"
# 3. germination abundance - "genus_abundance" column and "count" column
# 4. germination of fire followers - ask Rob how he would select for not present in CK but present in treated tray.


seedbank_load_raw <- read.csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022b/deg_seedbank_20230829.csv", header = TRUE, na.strings=c("","NA"))

seedbank_load_raw <- seedbank_load_raw %>%
  slice(1:2127) 

# below code doesn't work. I'm not sure why
seedbank_load_raw <- read.csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022b/deg_seedbank_20230829.csv", 
                              col_types = cols(
                                year = col_character(), 
                                stand = col_character(), 
                                site = col_character(),
                                soilcore = col_character(), 
                                depth_cm = col_character(), 
                                depth_name = col_character(),
                                treatment = col_character(), 
                                species_diversity = col_character(), 
                                genus_abundance = col_character(), 
                                lifeform = col_character(), 
                                status = col_character(), 
                                status_native = col_character(), 
                                status_nonnative = col_character(), 
                                lifescycle = col_character(), 
                                family = col_character(), 
                                count = col_integer(),
                                NOTES = col_character()
                              ))

view(seedbank_load_raw)

head(seedbank_load_raw)
str(seedbank_load_raw)
glimpse(seedbank_load_raw)

unique(seedbank_load_raw$stand)
unique(seedbank_load_raw$site)
unique(seedbank_load_raw$soilcore)
unique(seedbank_load_raw$depth_name)
unique(seedbank_load_raw$treatment)
unique(seedbank_load_raw$species_diversity)

#seedbank_load_raw <- seedbank_load_raw %>% 
#  filter(species != "Typha spp. ") # will OMIT Typha

#seedbank_load <- seedbank_load[seedbank_load$species != "Typha spp. ", ] # will REMOVE Typha from the df

INT_seedbank <- seedbank_load_raw %>% 
  filter(stand == "intact")

ENH_seedbank <- seedbank_load_raw %>% 
  filter(stand == "enhanced")

DEG_seedbank <- seedbank_load_raw %>% 
  filter(stand == "degraded")

```


# Fire following species

```{r fire followers only, include = TRUE}

control_spp = seedbank_load_raw$species_diversity[seedbank_load_raw$treatment=="control"]
charate_spp = seedbank_load_raw$species_diversity[seedbank_load_raw$treatment=="charate"]
oven_spp = seedbank_load_raw$species_diversity[seedbank_load_raw$treatment=="oven"]
ovenchar_spp = seedbank_load_raw$species_diversity[seedbank_load_raw$treatment=="ovenchar"]

firefollowers = unique(c(charate_spp, oven_spp, ovenchar_spp))

fire_only = tibble(firefollowers[!firefollowers %in% control_spp])
control_df = tibble(control_spp)

```

```{r intact seed bank, include = TRUE}

INT_speciesdiversity <- unique(INT_seedbank$species_diversity) # list of names
# 38 species
# [1] "Pseudognaphalium californicum" "Artemisia californica"         "Pseudognaphalium luteoalbum"   "Stipa lepida"                 
# [5] "Emmenanthe penduliflora"       "Eucrypta chrysanthemifolia"    "Nicotiana glauca"              "Bromus diandrus"              
# [9] NA                              "Polypogon monspeliensis"       "Erigeron canadensis"           "Malacothrix saxatilis"        
#[13] "Sonchus oleraceus"             "UnknownA"                      "Astragalus trichopodus"        "Claytonia parviflora"         
#[17] "Claytonia perfoliata"          "Ribes spp."                    "Apiastrum angustifolium"       "Cryptantha spp."              
#[21] "Bromus madritensis"            "Phacelia viscida"              "Festuca myuros"                "Acmispon glaber"              
#[25] "Solanum xanti"                 "Centaurea melitensis"          "Oxalis corniculata"            "Salvia leucophylla"           
#[29] "Laennecia coulteri"            "Marah macrocarpa"              "Malacothamnus fasciculatus"    "Melica imperfecta"            
#[33] "Carduus pycnocephalus"         "Ceanothus oliganthus"          "Phacelia tanacetifolia"        "Madia gracilis"               
#[37] "Typha domingensis"             "Uropappus lindleyi"            "Stephanomeria virgata"        

INT_seedbank %>% 
  group_by(status) %>% 
  summarise(species = species_diversity,
            N_native = unique(species_diversity))
  
  
INT_seedbank %>% 
  filter(status == "nonnative") %>% 
  summarize(N_nonnative = length(unique(species_diversity)))
  
```


```{r old code, include=FALSE}


seedbank_load <- seedbank_load_raw %>% 
  select(c("stand", "site", "soilcore", "depthname", "treatment", "species", "lifeform", "status", "lifecycle", "family", "totalcount"))
seedbank_load$totalcount <- as.numeric(seedbank_load$totalcount)
str(seedbank_load)

# load without unknowns and NAs <-- how do I omit UNKNOWNs?
seedbank_load %>%
  filter(!str_detect(species, "unk"), 
         !str_detect(species, "Typha spp.")) 

# rename treatments to be all lowercase 
seedbank_load <- seedbank_load %>% 
  mutate(treatment = recode(treatment,
                            Oven = 'oven',
                            Ovenchar = 'ovenchar',
                            Char = 'char',
                            Control = 'control', 
                            Native = 'native')
                            ) 
  
         
print(seedbank_load)
unique(seedbank_load$stand)
unique(seedbank_load$site)
unique(seedbank_load$soilcore)
unique(seedbank_load$depthname)
unique(seedbank_load$treatment)
unique(seedbank_load$species)
seedbank_load <- seedbank_load %>% 
  filter(species != "Typha spp. ") # will omit Typha

seedbank_load <- seedbank_load[seedbank_load$species != "Typha spp. ", ] # will remove Typha from the df

view(seedbank_load)

```