---
title: "ch1_standdeg_canopy"
author: "Stephanie Ma Lucero"
date: "2023-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install libraries, message=FALSE}

library(here) # similar to set working directory
library(tidyverse) # data wrangling - includes ggplot2, dplyr, tidyr, readr, purr, tibble, stringr, forcats
# library(lubridate) # dates and times
library(ggplot2) # data visualization
# library(readr)
library(dplyr)
library(ggthemes)
library(plotly)
library(ggpubr) # customize ggplot2 for publication
#library(broom)
#library(AICcmodavg)
library(vegan) #community ecology package - includes, MASS, cluster, mgcv
library(readxl) # for .xls and .xlsx sheets
#library(janitor)
library(multcompView) #Visualizations of Paired Comparisons, functions: TukeyHSD, dist{stats}, simint, simtest, csimint, csimtest{multcomp}, friedmanmc, kruskalmc{pgirmess}
#library(multcomp) # functions: multcompLetters2, multcompLetters3, multcompLetters4 using aov object

```

```{r install colors, include=TRUE}
devtools::install_github("an-bui/calecopal")

library(calecopal)
# all palettes
names(cal_palettes)

# Stand colors: INTACT, MATRIX, DEGRADED 
cal_palette(name = "chaparral3", n = 3, type = "continuous") 
deg <- "#D3E3CA"
mat <- "#92A587"
int <- "#2F3525"
standcolors <- c(int, mat, deg)

# Lifeform colors: shrub, grass, forb
cal_palette(name = "chaparral3", n = 3, type = "continuous") 
shrub <- "#D3E3CA"
grass <- "#92A587"
forb <- "#2F3525"
lifeformcolors <- c(int, mat, deg)

# Status colors: native, exotic 
cal_palette(name = "chaparral1", n = 6, type = "continuous") 
native <- "#AEBFA8"
exotic <- "#F19B34"
statuscolors <- c(native, exotic)

```

# 1. How does physical structure differ among the stands?

### 1.1 Percent cover by stand (horizontal variation)

```{r load csv, create columns, calculate - percent cover, echo=FALSE, eval=F}

# percent cover - belt transects, point intercept transects
abcover_full <- read.csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022b/deg_percentcover_byspecies_bylifeform.csv", header = TRUE, na.strings=c("","NA")) %>% 
  rename(speciescode = species.1 ) %>%
  mutate(standtype = fct_relevel(standtype, 
            "intact", "matrix", "degraded")) %>% 
  dplyr::select(!speciescode)
glimpse(abcover_full)
str(abcover_full)

#abcover_full$standtype <- factor(abcover_full$standtype, levels = c("intact", "matrix", "degraded"))

# convert dataframe to tibble
abcover_full_v <- as_tibble(abcover_full) 
class(abcover_full_v)

# combine site and rep to one column
abcover_full_v$site_rep <- paste(abcover_full_v$site, abcover_full_v$rep, sep="_") 

# combine site_rep and distance to one column
abcover_full_v$site_rep_dist <- paste(abcover_full_v$site_rep, abcover_full_v$distance, sep="_") 

# combine standtype and native/nonnative status to one column
abcover_full_v$stand_status <- paste(abcover_full_v$standtype, abcover_full_v$status, sep="_") 

view(abcover_full_v) # look at new columns

abcover_full_v %>%  
  na.omit() %>%  
  group_by(standtype, rep) %>% 
  summarize(data_points = length(rep))

# omit "ground" as a status since interested in Native and Non-native species 
abcover_full_v_omitground <- filter(abcover_full_v, status !="ground")
glimpse(abcover_full_v_omitground)
```

##### (A) by cover type - OMIT 
```{r calculate veg/ground cover, include = TRUE}
abcover_vegcover <- abcover_full_v %>% 
  filter(vertical == "1") %>% 
  group_by(standtype, site, rep) %>% 
  dplyr::summarize(count_per_transect = length(vertical), 
    percentcover_veg = length(vertical)/41, 
    percentcover_ground = (1-percentcover_veg)
    )
print(abcover_vegcover)

abcover_vegcover_long <- gather(abcover_vegcover, covertype, percentcover, percentcover_veg:percentcover_ground, factor_key = TRUE) 
abcover_vegcover_long

abcover_vegcover_meanSD <- abcover_vegcover_long %>%
  group_by(standtype, covertype) %>% 
  summarize(mean_cover = mean(percentcover),
            n = length((percentcover)),
            sd = sd(percentcover),
            se = ((sd(percentcover))/sqrt(length((percentcover)))))
print(abcover_vegcover_meanSD)
```
```{r aov veg/ground cover, include=TRUE}
summary(aov(percentcover_veg ~ standtype, data = abcover_vegcover))
TukeyHSD(aov(percentcover_veg ~ standtype, data = abcover_vegcover))
#$standtype
#                         diff         lwr        upr p adj
#matrix-intact    5.551115e-17 -0.02981350 0.02981350     1
#degraded-intact -5.551115e-17 -0.02981350 0.02981350     1
#degraded-matrix -1.110223e-16 -0.02434262 0.02434262     1

# I'm less interested in the amount of canopy openings
#summary(aov(percentcover ~ standtype * covertype, data = abcover_vegcover_long))
#TukeyHSD((aov(percentcover ~ standtype * covertype, data = abcover_vegcover_long)))
#$`standtype:covertype`
#                                                                diff         lwr         upr     p adj
#matrix:percentcover_veg-intact:percentcover_veg          0.008130081 -0.04407217  0.06033233 0.9963927 <-- max - int veg
#degraded:percentcover_veg-intact:percentcover_veg        0.028455285 -0.02374697  0.08065754 0.5537578 <-- deg - int veg
#intact:percentcover_ground-intact:percentcover_veg      -0.934959350 -0.99523732 -0.87468138 0.0000000
#matrix:percentcover_ground-intact:percentcover_veg      -0.943089431 -0.99529168 -0.89088718 0.0000000
#degraded:percentcover_ground-intact:percentcover_veg    -0.963414634 -1.01561689 -0.91121238 0.0000000
#degraded:percentcover_veg-matrix:percentcover_veg        0.020325203 -0.02229776  0.06294816 0.6828902 <-- deg - mat veg
#intact:percentcover_ground-matrix:percentcover_veg      -0.943089431 -0.99529168 -0.89088718 0.0000000
#matrix:percentcover_ground-matrix:percentcover_veg      -0.951219512 -0.99384247 -0.90859655 0.0000000
#degraded:percentcover_ground-matrix:percentcover_veg    -0.971544715 -1.01416768 -0.92892175 0.0000000
#intact:percentcover_ground-degraded:percentcover_veg    -0.963414634 -1.01561689 -0.91121238 0.0000000
#matrix:percentcover_ground-degraded:percentcover_veg    -0.971544715 -1.01416768 -0.92892175 0.0000000
#degraded:percentcover_ground-degraded:percentcover_veg  -0.991869919 -1.03449288 -0.94924696 0.0000000
#matrix:percentcover_ground-intact:percentcover_ground   -0.008130081 -0.06033233  0.04407217 0.9963927 <-- mat - int grd
#degraded:percentcover_ground-intact:percentcover_ground -0.028455285 -0.08065754  0.02374697 0.5537578 <-- deg - int grd
#degraded:percentcover_ground-matrix:percentcover_ground -0.020325203 -0.06294816  0.02229776 0.6828902 <-- deg - mat grd

# no significant difference in ground cover or in vegetation cover
```
```{r plot caonpy veg cover, include=TRUE}
#  column plot

abcover_vegcover_plot <- ggplot(abcover_vegcover_meanSD, aes(x = standtype, y = mean_cover, fill = covertype)) +
  geom_col(position = "dodge", width = 0.8) +
  geom_errorbar(
    aes(ymin=mean_cover-sd, ymax=mean_cover+sd), 
                width=.2, position=position_dodge(.9)) +
  labs(
    title = "Percent Canopy Cover", 
    x = "Stand Type", 
    y = "Average Percent Canopy Cover (%)") + # title, axes titles
  scale_fill_manual(values = c(standcolors)) + # manual colors
  # scale_fill_manual(values = cal_palette('chaparral2')) +  # continuous colors
  #                  limits = c("intact", "matrix", "degraded"), # "limits" reorders the x-axis
  #                  labels = c("Intact", "Matrix", "Degraded")) + # "labels" changes the name
  theme_bw() +
  scale_x_discrete(
    limits=c("intact", "matrix", "degraded"),
    labels=c("intact" = "Intact", "matrix" = "Matrix", "degraded" = "Degraded")
    )

abcover_vegcover_plot
```


##### (B) Percent cover by lifeform by native/nonnative status 

```{r cover x status x lifeform - data prep, include = TRUE}
# line 933 from Ch1_Degradation_original.Rmd

# data prep
abcover_bylf_bystatus <- abcover_full_v_omitground %>% 
  group_by(standtype, lifeform, status, site, rep, site_rep) %>% 
  dplyr::summarize(
    count_per_transect = n_distinct(site_rep_dist), 
    percentcover = n_distinct(site_rep_dist)/41
    )
view(abcover_bylf_bystatus) # prints to new tab

#write.csv(abcover_bylf_bystatus,"processed/percentcover_bystatus_bylifeform.csv")
cover_statuslf_matrix <- read.csv("percentcover_bystatus_bylifeform_matrix.csv", header = TRUE) %>% mutate(lifeform = case_when(lifeform == "herb" ~ "forb", 
                               TRUE ~ lifeform))
cover_statuslf_matrix <- cover_statuslf_matrix %>% 
  mutate(standtype = fct_relevel(standtype, 
            "intact", "matrix", "degraded"))
```

```{r cover by lf by status - stats, include=TRUE}
# SHRUB
# highlight all and run as one command
abcover_bylf_bystatus_aov_shrub <- aov(percentcover ~ standtype * status, data = cover_statuslf_matrix %>% 
                                   filter((lifeform == 'shrub')))

abcover_bylf_bystatus_aov_shrubnat <- aov(percentcover ~ standtype, data = cover_statuslf_matrix %>% 
                                   filter((lifeform == 'shrub')) %>%  
                                  filter((status == 'native')))
print(summary(abcover_bylf_bystatus_aov_shrubnat))
#            Df Sum Sq Mean Sq F value   Pr(>F)    
#standtype    2 0.5516 0.27581    13.9 0.000752 ***
#Residuals   12 0.2382 0.01985 
print(TukeyHSD(abcover_bylf_bystatus_aov_shrubnat))
#$standtype
#                      diff        lwr         upr     p adj
#intact-degraded  0.5162602  0.2505030  0.78201736 0.0006178
#matrix-degraded  0.2439024  0.0269126  0.46089228 0.0277839
#matrix-intact   -0.2723577 -0.5381149 -0.00660053 0.0444896
# significant differences in native shrub cover among stands


# FORB
abcover_bylf_bystatus_aov_forb <- aov(percentcover ~ standtype * status, data = cover_statuslf_matrix %>% filter((lifeform == 'forb')))
print(summary(abcover_bylf_bystatus_aov_forb))
print(TukeyHSD(abcover_bylf_bystatus_aov_forb))
## forb - native
abcover_bylf_bystatus_aov_forbnat <- aov(percentcover ~ standtype, data = cover_statuslf_matrix %>% filter((lifeform == 'forb')) %>% filter((status == 'native')))
print(summary(abcover_bylf_bystatus_aov_forbnat))
# Df  Sum Sq  Mean Sq F value Pr(>F)
#standtype    2 0.00512 0.002558   0.905   0.43
#Residuals   12 0.03391 0.002826  
print(TukeyHSD(abcover_bylf_bystatus_aov_forbnat))
#$standtype
#                      diff         lwr       upr     p adj
#intact-degraded 0.02845528 -0.07182408 0.1287347 0.7352620
#matrix-degraded 0.04065041 -0.04122735 0.1225282 0.4091252
#matrix-intact   0.01219512 -0.08808424 0.1124745 0.9438944 
# NO SIG differences
# forb - nonnative
abcover_bylf_bystatus_aov_forbnn <- aov(percentcover ~ standtype, data = cover_statuslf_matrix %>% filter((lifeform == 'forb')) %>% filter((status == 'nonnative')))
print(summary(abcover_bylf_bystatus_aov_forbnn))
#    Df Sum Sq Mean Sq F value   Pr(>F)    
#standtype    2 0.6180 0.30901    13.3 0.000904 ***
#Residuals   12 0.2789 0.02324    
print(TukeyHSD(abcover_bylf_bystatus_aov_forbnn))
#$standtype
#                      diff        lwr        upr     p adj
#intact-degraded -0.5081301 -0.7957264 -0.2205337 0.0013474 <-- Int - Deg
#matrix-degraded -0.3373984 -0.5722198 -0.1025769 0.0062271 <-- Mat - Deg
#matrix-intact    0.1707317 -0.1168647  0.4583281 0.2896736

# GRASS
abcover_bylf_bystatus_aov_grass <- aov(percentcover ~ standtype * status, data = cover_statuslf_matrix %>% 
                                   filter((lifeform == 'grass')))
print(summary(abcover_bylf_bystatus_aov_grass))
print(TukeyHSD(abcover_bylf_bystatus_aov_grass))
## grass - native
abcover_bylf_bystatus_aov_grassnat <- aov(percentcover ~ standtype, data = cover_statuslf_matrix %>% filter((lifeform == 'grass')) %>% filter((status == 'native')))
print(summary(abcover_bylf_bystatus_aov_grassnat))
# print(summary(abcover_bylf_bystatus_aov_grassnat))
#            Df Sum Sq Mean Sq F value   Pr(>F)    
#standtype    2 0.6728  0.3364   30.36 2.02e-05 ***
#Residuals   12 0.1330  0.0111  
print(TukeyHSD(abcover_bylf_bystatus_aov_grassnat))
#$standtype
#                       diff         lwr        upr     p adj
#intact-degraded  0.56097561  0.36240594  0.7595453 0.0000191 <-- Int - Deg
#matrix-degraded  0.07723577 -0.08489569  0.2393672 0.4370582
#matrix-intact   -0.48373984 -0.68230951 -0.2851702 0.0000808 <-- Int - Mat
# SIG MORE native grass at Intact
# nonnative
abcover_bylf_bystatus_aov_grassnn <- aov(percentcover ~ standtype, data = cover_statuslf_matrix %>% filter((lifeform == 'grass')) %>% filter((status == 'nonnative')))
print(summary(abcover_bylf_bystatus_aov_grassnn))
#            Df Sum Sq Mean Sq F value   Pr(>F)    
#standtype    2 1.3178  0.6589   55.46 8.66e-07 ***
#Residuals   12 0.1426  0.0119 
print(TukeyHSD(abcover_bylf_bystatus_aov_grassnn))
#$standtype
#                      diff        lwr         upr     p adj
#intact-degraded -0.8089431 -1.0145691 -0.60331712 0.0000006 <-- 
#matrix-degraded -0.2195122 -0.3874051 -0.05161929 0.0115409 <--
#matrix-intact    0.5894309  0.3838049  0.79505687 0.0000165 <-- 
# SIG different non-native grass among sites

# FERN
abcover_bylf_bystatus_aov_fern <- aov(percentcover ~ standtype * status, data = cover_statuslf_matrix %>% 
                                   filter((lifeform == 'fern')))
print(summary(abcover_bylf_bystatus_aov_fern))
print(TukeyHSD(abcover_bylf_bystatus_aov_fern))
## fern - native
abcover_bylf_bystatus_aov_fernnat <- aov(percentcover ~ standtype, data = cover_statuslf_matrix %>% filter((lifeform == 'fern')) %>% filter((status == 'native')))
print(summary(abcover_bylf_bystatus_aov_fernnat))
print(TukeyHSD(abcover_bylf_bystatus_aov_fernnat))
#$standtype <-- can't really do stats on only one occurrence
#                         diff          lwr         upr   p adj
#intact-degraded  8.130081e-03 -0.002714893 0.018975056 0.15458 
#matrix-degraded  1.662443e-18 -0.008854884 0.008854884 1.00000
#matrix-intact   -8.130081e-03 -0.018975056 0.002714893 0.15458
# nonnative
abcover_bylf_bystatus_aov_fernnn <- aov(percentcover ~ standtype, data = cover_statuslf_matrix %>% filter((lifeform == 'fern')) %>% filter((status == 'nonnative')))
print(summary(abcover_bylf_bystatus_aov_fernnn))
print(TukeyHSD(abcover_bylf_bystatus_aov_fernnn))

abcover_bylf_bystatus_meanSD <- cover_statuslf_matrix %>%  
  group_by(lifeform, status, standtype) %>% 
  summarize(avg_cover = mean(percentcover), 
            sd = sd(percentcover),
            N = length(percentcover), 
            se = ((sd(percentcover))/sqrt(length((percentcover)))))

abcover_bylf_bystatus_meanSD$status_lifeform <- paste(abcover_bylf_bystatus_meanSD$status, abcover_bylf_bystatus_meanSD$lifeform, sep="_") # combine status and life form to one column
print(abcover_bylf_bystatus_meanSD) 
```

```{r plot abcover_bylf_meanSD, include = TRUE}
# line 965 in Ch1_Degradation_original.Rmd

#  column plot, 2 x 2 by lifeform
abcover_bylf_bystatus_meanSD_plot_wrap <- ggplot(abcover_bylf_bystatus_meanSD, aes(x = status, y = avg_cover, fill = standtype )) +
  facet_wrap(~ lifeform) +
  geom_col(position = "dodge", width = 0.8) +
  geom_errorbar(aes(ymin=avg_cover-se, ymax=avg_cover+se), width=.2,
                 position=position_dodge(.9)) +
  labs(title = "Percent Cover by status and standtype", x = "Status", y = "Average Percent Cover (%)") +
  scale_fill_manual(values = c(standcolors)) + # manual colors
#   scale_fill_manual(values = cal_palette('chaparral3')) + # continuous colors
                       theme_bw()

abcover_bylf_bystatus_meanSD_plot_wrap + scale_x_discrete(limits=c("intact", "matrix", "degraded"),
                                         labels=c("intact" = "Intact", "matrix" = "Matrix", "degraded" = "Degraded"))


```

### 1.2 Canopy height (vertical variation)

```{r load csv - canopy height, include=TRUE}
# stand height 

standheight_full <- read_csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022b/deg_maxheight.csv",
                             col_types = cols(
                               standtype = col_character(),
                               site = col_character(),
                               Transect_rep = col_character(),
                               Reading = col_character(),
                               Species = col_character(),
                               height_cm = col_double(),
                               next_tallest = col_character())) %>%
  dplyr::select('standtype', 'site', 'Transect_rep', 'Reading', 'Species', 'height_cm') %>% 
  rename(rep = Transect_rep, 
         reading = Reading, 
         species = Species) %>% 
  mutate(standtype = fct_relevel(standtype, "Intact", "Matrix", "Degraded")) %>% 
  filter(site!= "Intact_4")
view(standheight_full)

standheight_full %>%  
  group_by(site,rep) %>% 
  summarize(data_points = length(reading))
```

```{r combine columns - canopy height, include = TRUE}

standheight_full$site_rep <- paste(standheight_full$site, standheight_full$rep, sep="_") # combine site and rep to one column

standheight_siterep_meanSD <- standheight_full %>%
  group_by(standtype, site_rep) %>%
  summarize(mean_height = mean(height_cm),
            n = length((height_cm)),
            sd = sd(height_cm),
            se = ((sd(height_cm))/sqrt(length((height_cm))))) %>% 
  print(standheight_siterep_meanSD)

standheight_meanSD <- standheight_full %>%
  group_by(standtype, rep) %>%
  summarize(mean_height_byrep = mean(height_cm),
            n = length((height_cm)),
            sd = sd(height_cm),
            se = ((sd(height_cm))/sqrt(length((height_cm))))) %>% 
  group_by(standtype) %>% 
   summarize(mean_height_bystandtype_cm = mean(mean_height_byrep),
   n = length((mean_height_byrep)),
            sd_cm = sd(mean_height_byrep),
            se_cm = ((sd(mean_height_byrep))/sqrt(length((mean_height_byrep))))) %>%
  print(standheight_meanSD)

# standtype mean_height_bystandtype N SD SE
#Intact	  150.29268	3	62.942199	36.339695
#Matrix	  90.17480	6	30.885894	12.609114
#Degraded	94.00813	6	6.593106	2.691624

```

```{r stand height - stats, include=TRUE}

standheight_siterep_standtype_aov <- aov((mean_height_cm ~ standtype) , data = standheight_siterep_meanSD)
summary.aov(standheight_siterep_standtype_aov)

standheight_siterep_standtype_tukey <- TukeyHSD(standheight_siterep_standtype_aov, conf.level=.95) 
print(standheight_siterep_standtype_tukey)

```




```{r}
# species richness, native richness
abrich_full <- read.csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022b/deg_abrich.csv", header = TRUE, na.strings=c("","NA")) %>% 
  dplyr::select('trasecttype', 'standtype', 'site', 'rep', 'distance', 'vertical', 'species', 'lifeform', 'status', 'lifecycle', 'Family', 'lifestage') %>% 
  rename(transecttype = trasecttype, 
         family = Family)
glimpse(abrich_full)

# native shrub density 
shrubdensitylife_full <- read_csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022b/deg_beltdensity_bylifestage.csv", 
    col_types = cols(
      StandType = col_character(), 
      Site = col_character(),
      rep = col_integer(),
      ScientificName = col_character(), 
      dead = col_integer(),
      immature = col_integer(),
      mature = col_integer(), 
      resprout = col_integer(), 
      seedling = col_integer()
      )
     ) %>% 
  rename()
  


shrubdensityspp_full <- read_csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/chaparraldegradation_2022b/deg_beltdensity_byspecies.csv")
# shrubdensityalive_full <- read_csv("~/Dropbox/GRADSCHOOL/Dissertation/R_dissertation/deg_beltdensity_seperatealive.csv")

```
