---
title: "ch1_standdeg_seedbank"
author: "Stephanie Ma Lucero"
date: "2023-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install libraries, include=TRUE}
library(here) # similar to set working directory
library(tidyverse) # data wrangling - includes ggplot2, dplyr, tidyr, readr, purr, tibble, stringr, forcats
library(ggplot2) # data visualization
library(dplyr)
library(ggthemes)
library(plotly)
library(ggpubr) # customize ggplot2 for publication
library(vegan) #community ecology package - includes, MASS, cluster, mgcv
library(readxl) # for .xls and .xlsx sheets
library(multcompView) #Visualizations of Paired Comparisons, functions: TukeyHSD, dist{stats}, simint, simtest, csimint, csimtest{multcomp}, friedmanmc, kruskalmc{pgirmess}
```

# Load data

```{r load seedbank data, include=TRUE}

# STAND COMPARISONS BY SEEDBANK SPECIES RICHNESS AND GERMINATION COUNTS - OMIT Zeros
# 1. species richness - use "species_richness" column 
# 2. native species richness - filter status == "native"
# 3. germination abundance - "genus_abundance" column and "count" column
# 4. germination of fire followers - ask Rob how he would select for not present in CK but present in treated tray.

#seedbank_load_raw <- read.csv("deg_seedbank_20231007.csv", header = TRUE, na.strings=c("","NA"))
#seedbank_load_slice <- seedbank_load_raw %>% slice(1:2127) 

germination_m2_raw <- read_xlsx("processed/germination_m2.xlsx")

germination_m2_raw_edit <- germination_m2_raw %>%
  mutate(site = fct_relevel(site, 
            "INT1", "INT2", "INT3","ENH1", "ENH2", "DEG1", "DEG2")) %>% 
  mutate(treatment = fct_relevel(treatment, 
                                 "control", "charate", "oven", "ovenchar")) %>% 
  dplyr::select(c(stand, site, soilcore, depth_name, treatment, rep, species_diversity, genus_abundance, lifeform, status, lifescycle, family, stand_core, stand_core_depth, stand_core_depth_treat, n_per_m2))

glimpse(germination_m2_raw_edit)
```
```{r data prep}
seedbank_load_w <- germination_m2_raw_edit %>%
  mutate(#year = as.character(year),
                                stand = as.character(stand), 
                                site = as.character(site),
                                soilcore = as.character(soilcore), 
                                depth_name = as.character(depth_name), 
                                treatment = as.character(treatment), 
                                rep = as.integer(rep),                        
                                species_diversity = as.character(species_diversity), 
                                genus_abundance = as.character(genus_abundance), 
                                lifeform = as.character(lifeform), 
                                status = as.character(status), 
                                lifescycle = as.character(lifescycle), 
                                family = as.character(family),
                                n_per_m2 = as.integer(n_per_m2)
                              ) %>%
  mutate(stand = fct_relevel(stand, 
            "intact", "enhanced", "degraded")) %>% 
  mutate(treatment = fct_relevel(treatment, 
                                 "control", "charate", "oven", "ovenchar"))
  # #mutate(stand = fct_recode(stand, 
  #                               "shrub_dominated" = "intact", # rename stand types
  #                               "matrix" = "enhanced",
  #                               "grass_dominated" = "degraded"))

tail(seedbank_load_w)

# combine SITE and CORE to one column
seedbank_load_w$stand_core <- paste(seedbank_load_w$site, seedbank_load_w$soilcore, sep="_") 

# combine SITE_CORE and DEPT to one column
seedbank_load_w$stand_core_depth <- paste(seedbank_load_w$stand_core, seedbank_load_w$depth_name, sep="_") 

# combine SITE_CORE_DEPTH and TREATMENT to one column
seedbank_load_w$stand_core_depth_treat <- paste(seedbank_load_w$stand_core_depth, seedbank_load_w$treatment, sep="_") 

# combine SITE_CORE and TREATMENT to one column
seedbank_load_w$stand_core_treat <- paste(seedbank_load_w$stand_core, seedbank_load_w$treatment, sep="_") 

seedbank_load_w <- seedbank_load_w %>% 
  mutate(stand_core = fct_relevel(stand_core, 
                                  "INT1_1", "INT1_2" , "INT1_3" ,"INT2_4"  ,"INT2_5" , "INT2_6",  "INT3_7" , "INT3_8" , "INT3_9",
                                  "ENH1_1" , "ENH1_2" , "ENH1_3" , "ENH1_4" , "ENH1_5" , "ENH2_6" , "ENH2_7" , "ENH2_8"  ,"ENH2_9"  ,"ENH2_10", 
                                 "DEG1_1" , "DEG1_2"  ,"DEG1_3"  ,"DEG1_4" , "DEG2_5" , "DEG2_6" , "DEG2_7" ))  %>% 
  mutate(site = fct_relevel(site, "INT1", "INT2", "INT3", "ENH1", "ENH2", "DEG1", "DEG2"))

unique(seedbank_load_w$stand)
unique(seedbank_load_w$site)
unique(seedbank_load_w$soilcore)
unique(seedbank_load_w$depth_name)
unique(seedbank_load_w$treatment)
sort(unique(seedbank_load_w$species_diversity))
unique(seedbank_load_w$status)
unique(seedbank_load_w$stand_core_depth)
unique(seedbank_load_w$stand_core_treat) # wrap by treatment instead of ordering


#head(seedbank_load_v)
str(seedbank_load_w)
glimpse(seedbank_load_w)


#seedbank_load_v <- seedbank_load_v %>% 
#  filter(treatment != "pretreatment") # will OMIT species from pretreatment


```

```{r slice by stand type, include=TRUE}

INT_seedbank <- seedbank_load_w %>% 
  filter(stand == "intact")
unique(INT_seedbank$site)

ENH_seedbank <- seedbank_load_w %>% 
  filter(stand == "enhanced")
unique(ENH_seedbank$site)

DEG_seedbank <- seedbank_load_w %>% 
  filter(stand == "degraded")
unique(DEG_seedbank$site)
```

# Fire following species

```{r fire followers only, include = TRUE}

control_spp = seedbank_load_w$species_diversity[seedbank_load_w$treatment=="control"]
sort(unique(control_spp))

charate_spp = seedbank_load_w$species_diversity[seedbank_load_w$treatment=="charate"]
sort(unique(charate_spp))

oven_spp = seedbank_load_w$species_diversity[seedbank_load_w$treatment=="oven"]
sort(unique(oven_spp))

ovenchar_spp = seedbank_load_w$species_diversity[seedbank_load_w$treatment=="ovenchar"]
sort(unique(ovenchar_spp))

germinpretreatmenttray = unique(c(charate_spp, oven_spp, ovenchar_spp))

fire_only = tibble(germinpretreatmenttray[!germinpretreatmenttray %in% control_spp])
control_df = tibble(control_spp)
glimpse(fire_only) #17 species

#rename column header
names(fire_only)[names(fire_only) == "germinpretreatmenttray[!germinpretreatmenttray %in% control_spp]"] <- "species_diversity"

print(fire_only) # species list
```



```{r fire followers by site total emergence, include=TRUE}

#left join data frames to create complete df of fire following species
seedbank_fire <- left_join(fire_only, seedbank_load_w, by =  "species_diversity")
unique(seedbank_fire$species_diversity)
```

```{r explore fire follwoing seedbanks, include=TRUE}
seedbank_fire %>% 
  na.omit() %>%
  group_by(species_diversity) %>%  # group by species totals
  summarise(sum_germination_Nperm2 = sum(n_per_m2))

seedbank_fire %>% 
  na.omit() %>%
  group_by(depth_name) %>%  # group by soil depth
  summarise(sum_germination = sum(n_per_m2))
# depth_name  sum_germination
# surface	    6,170	
# deep	      3,255			

seedbank_fire %>% 
  na.omit() %>%
  group_by(treatment) %>%  # group by soil depth
  summarise(sum_germination_Nperm2 = sum(n_per_m2))
# treatment  sum_germination
# charate	    3,119			
# oven	      2,762			
# ovenchar	  3,544	

seedbank_fire %>% 
  na.omit() %>%
  group_by(lifeform) %>%  # group by lifeform
  summarise(sum_germination_Nperm2 = sum(n_per_m2))
# lifeform  sum_germination
# forb	    6,728			
# shrub	    2,697	

seedbank_fire %>% 
  na.omit() %>%
  group_by(site) %>%  # group by site
  summarise(sum_germination_Nperm2 = sum(n_per_m2))
# site    sum_germination_perm2
# INT1  	2,466			
# INT2	  1,571			
# INT3	  2,538			
# ENH1	  1,254			
# ENH2	  1,596	

seedbank_fire %>% 
  na.omit() %>%
  group_by(site, lifeform) %>%  # group by lifeform and site
  summarise(sum_germination_Nperm2 = sum(n_per_m2))
# site  lifeform  sum_germination_Nperm2
# INT1	forb	    767		
# INT1	shrub	    1,699		
# INT2	forb	    1,371		
# INT2	shrub	    200		
# INT3	forb	    2,538		
# ENH1	forb    	570		
# ENH1	shrub	    684		
# ENH2	forb	    1,482		
# ENH2	shrub	    114	

seedbank_fire %>% 
  na.omit() %>%
  filter(lifeform == "shrub") %>% # only shrubs
  group_by(site) %>%  # group by site
  summarise(sum_germination_Nperm2 = sum(n_per_m2))
#  site     shrub_germ_countperm2
#  INT1	    1,699			
#  INT2	    200			
#  ENH1	    684			
#  ENH2	    114	

seedbank_fire %>% 
  na.omit() %>%
  filter(lifeform == "forb") %>% # only forbs
  group_by(site) %>%  # group by site
  summarise(sum_germination_Nperm2 = sum(n_per_m2))
# site    forb_germ_countperm2
# INT1	  767			
# INT2	  1,371			
# INT3	  2,538			
# ENH1	  570			
# ENH2	  1,482	


seedbank_fire_totalemerg <- seedbank_fire %>% 
  na.omit() %>%
  group_by(stand, stand_core) %>% 
  summarise(sum_germination_Nperm2 = sum(n_per_m2))


```

```{r fire followers plot, include = TRUE}
# bar plot
seedbank_fire_plot <- ggplot(seedbank_fire_totalemerg, aes(x = stand_core, y = sum, fill = stand)) +
  geom_col(position = "dodge", width = 0.8) +
  labs(
    title = "Total emergence of species following fire", 
    x = "Site", 
    y = "Total emergence (N)") + # title, axes titles
  scale_fill_manual(values = c(standcolors)) + # manual colors
  # scale_fill_manual(values = cal_palette('chaparral2')) +  # continuous colors
  #                  limits = c("intact", "matrix", "degraded"), # "limits" reorders the x-axis
  #                  labels = c("Intact", "Matrix", "Degraded")) + # "labels" changes the name
  theme_bw() +
 # scale_x_discrete(
 #   limits=c("intact", "matrix", "degraded"),
 #   labels=c("intact" = "Intact", "matrix" = "Matrix", "degraded" = "Degraded")
 #   )
  scale_y_continuous(breaks = seq(0, max(seedbank_fire_totalemerg$sum), by = 1))
 
seedbank_fire_plot +
  theme(axis.text.x = element_text(angle = 45
                                  , hjust = 1))

seedbank_fire %>% 
  group_by(stand_core) %>% 
  summarise(sum = sum(count))
```

# SHRUB - species diversity

```{r SHRUB diversity, include = TRUE}

INT_speciesdiversity <- unique(SHRUB_seedbank$species_diversity) # list of names
print(INT_speciesdiversity)

# 39 species

#  [1] "Bromus diandrus"               "Claytonia parviflora"         
#  [3] "Emmenanthe penduliflora"       "Eucrypta chrysanthemifolia"   
#  [5] "Pseudognaphalium luteoalbum"   "Stipa lepida"                 
#  [7] "Unknown A - shrub"             "Astragalus trichopodus"       
#  [9] "Claytonia perfoliata"          "Nicotiana glauca"             
# [11] "Polypogon monspeliensis"       "Pseudognaphalium californicum"
# [13] "Sonchus oleraceus"             "Erigeron canadensis"          
# [15] "Malacothrix saxatilis"         "Artemisia californica"        
# [17] "Ribes spp."                    "Apiastrum angustifolium"      
# [19] "Cryptantha spp."               "Bromus madritensis"           
# [21] "Festuca myuros"                "Phacelia viscida"             
# [23] "Acmispon glaber"               "Bromus spp."                  
# [25] "Solanum xanti"                 "Centaurea melitensis"         
# [27] "Laennecia coulteri"            "Oxalis corniculata"           
# [29] "Salvia leucophylla"            "Marah macrocarpa"             
# [31] "Ceanothus oliganthus"          "Malacothamnus fasciculatus"   
# [33] "Melica imperfecta"             "Carduus pycnocephalus"        
# [35] "Phacelia tanacetifolia"        "Typha domingensis"            
# [37] "Madia gracilis"                "Uropappus lindleyi"           
# [39] "Stephanomeria virgata"            



SHRUB_seedbank %>% 
  group_by(status) %>% 
   summarize(N = length(unique(species_diversity)))
# status  N
# native	28			
# nonnative	11	

# NATIVE SPP
INT_speciesdiversity_native <-(SHRUB_seedbank %>% 
  filter(status == "native"))
INT_speciesdiversity_native_unique <- unique(INT_speciesdiversity_native$species_diversity)
print(INT_speciesdiversity_native_unique)
#  [1] "Claytonia parviflora"          "Emmenanthe penduliflora"      
#  [3] "Eucrypta chrysanthemifolia"    "Stipa lepida"                 
#  [5] "Unknown A - shrub"             "Astragalus trichopodus"       
#  [7] "Claytonia perfoliata"          "Pseudognaphalium californicum"
#  [9] "Erigeron canadensis"           "Malacothrix saxatilis"        
# [11] "Artemisia californica"         "Ribes spp."                   
# [13] "Apiastrum angustifolium"       "Cryptantha spp."              
# [15] "Phacelia viscida"              "Acmispon glaber"              
# [17] "Solanum xanti"                 "Laennecia coulteri"           
# [19] "Salvia leucophylla"            "Marah macrocarpa"             
# [21] "Ceanothus oliganthus"          "Malacothamnus fasciculatus"   
# [23] "Melica imperfecta"             "Phacelia tanacetifolia"       
# [25] "Typha domingensis"             "Madia gracilis"               
# [27] "Uropappus lindleyi"            "Stephanomeria virgata" 

INT_speciesdiversity_nn <-(SHRUB_seedbank %>% 
  filter(status == "nonnative"))
INT_speciesdiversity_nn_unique <- unique(INT_speciesdiversity_nn$species_diversity)
print(INT_speciesdiversity_nn_unique)  
# 1] "Bromus diandrus"             "Pseudognaphalium luteoalbum"
#  [3] "Nicotiana glauca"            "Polypogon monspeliensis"    
#  [5] "Sonchus oleraceus"           "Bromus madritensis"         
#  [7] "Festuca myuros"              "Bromus spp."                
#  [9] "Centaurea melitensis"        "Oxalis corniculata"         
# [11] "Carduus pycnocephalus"
```

```{r MATRIX seed bank, include=TRUE}
MATRIX_speciesdiversity <- unique(MATRIX_seedbank$species_diversity) # list of names
print(MATRIX_speciesdiversity)

# 41 species

# [1] "Bromus madritensis"                             
#  [2] "Centaurea melitensis"                           
#  [3] "Eriodictyon crassifolium"                       
#  [4] "Salvia leucophylla "                            
#  [5] "Typha domingensis"                              
#  [6] "Acmispon maritimus"                             
#  [7] "Malacothamnus fasciculatus"                     
#  [8] "Artemisia californica"                          
#  [9] "Diplacus aurantiacus"                           
# [10] "Sonchus oleraceus"                              
# [11] "Festuca myuros "                                
# [12] "Lactuca serriola "                              
# [13] "Hirschfeldia incana"                            
# [14] "Calochortus clavatus"                           
# [15] "Acmispon glaber"                                
# [16] "Erodium spp. "                                  
# [17] "Pseudognaphalium luteoalbum"                    
# [18] "Emmenanthe penduliflora"                        
# [19] "Logfia filaginoides"                            
# [20] "Stipa lepida"                                   
# [21] "Uropappus lindleyi"                             
# [22] "Asclepias fascicularis"                         
# [23] "Bromus hordeaceus"                              
# [24] "Juncus bufonius"                                
# [25] "Phacelia spp."                                  
# [26] "Festuca myuros"                                 
# [27] "Astragalus trichopodus "                        
# [28] "Avena barbara"                                  
# [29] "Bromus diandrus"                                
# [30] "Dipterostemon capitatus"                        
# [31] "Unknown D - brown dicot"                        
# [32] "Unknown C - bright green seedling, small leaves"
# [33] "Trifolium spp."                                 
# [34] "Acmispon strigosus"                             
# [35] "Thysanocarpus spp. "                            
# [36] "Stephanomeria virgata"                          
# [37] "Unknown E - plastic plant"                      
# [38] "Unknown G - fuzzy leaf dicot"                   
# [39] "Trifolium willdenovii"                          
# [40] "Lupinus bicolor "                               
# [41] "Solanum xanti"   

MATRIX_seedbank %>% 
  group_by(status) %>% 
   summarize(N = length(unique(species_diversity)))

# status    N
# native	  28			
# nonnative	12			
# unknown	  1	
```

```{r GRASS seed bank, include=TRUE}
GRASS_speciesdiversity <- unique(GRASS_seedbank$species_diversity) # list of names
print(GRASS_speciesdiversity)

# 20 species

# [1] "Astragalus trichopodus"      "Bromus madritensis"         
#  [3] "Emmenanthe penduliflora"     "Erodium cicutarium"         
#  [5] "Hirschfeldia incana"         "Erodium moschatum"          
#  [7] "Croton setiger"              "Nicotiana glauca"           
#  [9] "Bromus diandrus"             "Artemisia californica"      
# [11] "Acmispon maritimus"          "Centaurea melitensis"       
# [13] "Pseudognaphalium luteoalbum" "Trifolium gracelentum"      
# [15] "Galium porrigens"            "Fragaria vesca"             
# [17] "Malacothamnus fasciculatus"  "Eucrypta chrysanthemifolia" 
# [19] "Cryptantha spp."             "Erigeron canadensis"       

GRASS_seedbank %>% 
  group_by(status) %>% 
   summarize(N = length(unique(species_diversity)))
# status    N
# native	  12			
# nonnative	8	
```

# stand differences
```{r}
seedbank_native <- seedbank_load_v%>% 
  filter(status == "native") %>% 
  group_by(stand, stand_core) %>% 
  summarize(total_native_emergence = sum(count))
view(seedbank_native)

# bar plot
seedbank_native_plot <- ggplot(seedbank_native, aes(x = stand_core, y = total_native_emergence, fill = stand)) +
  geom_col(position = "dodge", width = 0.8) +
  labs(
    title = "Total emergence of native species", 
    x = "Site", 
    y = "Total emergence (N)") + # title, axes titles
  scale_fill_manual(values = c(standcolors)) + # manual colors
  # scale_fill_manual(values = cal_palette('chaparral2')) +  # continuous colors
  #                  limits = c("intact", "matrix", "degraded"), # "limits" reorders the x-axis
  #                  labels = c("Intact", "Matrix", "Degraded")) + # "labels" changes the name
  theme_bw() #+
 # scale_x_discrete(
 #   limits=c("intact", "matrix", "degraded"),
 #   labels=c("intact" = "Intact", "matrix" = "Matrix", "degraded" = "Degraded")
 #   )
 
seedbank_native_plot +
  theme(axis.text.x = element_text(angle = 90
                                  , hjust = 1))
```

