---
title: "ch1_standdeg_seedbank"
author: "Stephanie Ma Lucero"
date: "2023-12-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install libraries, include=TRUE}
library(here) # similar to set working directory
library(tidyverse) # data wrangling - includes ggplot2, dplyr, tidyr, readr, purr, tibble, stringr, forcats
library(ggplot2) # data visualization
library(dplyr)
library(ggthemes)
library(plotly)
library(ggpubr) # customize ggplot2 for publication
library(vegan) #community ecology package - includes, MASS, cluster, mgcv
library(readxl) # for .xls and .xlsx sheets
library(multcompView) #Visualizations of Paired Comparisons, functions: TukeyHSD, dist{stats}, simint, simtest, csimint, csimtest{multcomp}, friedmanmc, kruskalmc{pgirmess}
library(skimr)
#library(mass)
```

# Load data

```{r load seedbank data, include=TRUE}

# STAND COMPARISONS BY SEEDBANK SPECIES RICHNESS AND GERMINATION COUNTS - OMIT Zeros
# 1. species richness - use "species_richness" column 
# 2. native species richness - filter status == "native"
# 3. germination abundance - "genus_abundance" column and "count" column
# 4. germination of fire followers - ask Rob how he would select for not present in CK but present in treated tray.

#seedbank_load_raw <- read.csv("deg_seedbank_20231007.csv", header = TRUE, na.strings=c("","NA"))
#seedbank_load_slice <- seedbank_load_raw %>% slice(1:2127) 

germination_m2_load <- read_xlsx("processed/germination_m2.xlsx")
glimpse(germination_m2_load)

seedbank <- germination_m2_load %>%
  mutate(site = fct_relevel(site, 
            "INT1", "INT2", "INT3","ENH1", "ENH2", "DEG1", "DEG2")) %>% 
  mutate(treatment = fct_relevel(treatment, 
                                 "control", "charate", "oven", "ovenchar")) %>% 
  dplyr::select(c(stand, site, soilcore, depth_name, subsample_cm3, subsample_g,treatment, rep, species_diversity, genus_abundance, lifeform, status, lifescycle, family, count, stand_core, stand_core_depth, stand_core_depth_treat, n_per_cm3, n_per_m3, n_per_g, n_per_kg))

#glimpse(seedbank)

seedbank <- seedbank %>%
  mutate(#year = as.character(year),
                                stand = as.character(stand), 
                                site = as.character(site),
                                soilcore = as.character(soilcore), 
                                depth_name = as.character(depth_name),
                                treatment = as.character(treatment), 
                                rep = as.integer(rep),                        
                                species_diversity = as.character(species_diversity), 
                                genus_abundance = as.character(genus_abundance), 
                                lifeform = as.character(lifeform), 
                                status = as.character(status), 
                                lifescycle = as.character(lifescycle), 
                                family = as.character(family),
                                count = as.integer(count)
                              ) %>%
  mutate(stand = fct_relevel(stand, 
            "intact", "enhanced", "degraded")) %>% 
  mutate(treatment = fct_relevel(treatment, 
                                 "control", "charate", "oven", "ovenchar"))
  # #mutate(stand = fct_recode(stand, 
  #                               "shrub_dominated" = "intact", # rename stand types
  #                               "matrix" = "enhanced",
  #                               "grass_dominated" = "degraded"))

seedbank <- seedbank %>% 
  mutate(stand_core = fct_relevel(stand_core, 
                                  "INT1_1", "INT1_2" , "INT1_3" ,"INT2_4"  ,"INT2_5" , "INT2_6",  "INT3_7" , "INT3_8" , "INT3_9",
                                  "ENH1_1" , "ENH1_2" , "ENH1_3" , "ENH1_4" , "ENH1_5" , "ENH2_6" , "ENH2_7" , "ENH2_8"  ,"ENH2_9"  ,"ENH2_10", 
                                 "DEG1_1" , "DEG1_2"  ,"DEG1_3"  ,"DEG1_4" , "DEG2_5" , "DEG2_6" , "DEG2_7" ))  %>% 
  mutate(site = fct_relevel(site, "INT1", "INT2", "INT3", "ENH1", "ENH2", "DEG1", "DEG2"))


seedbank$stand_core_treat <- paste(seedbank$stand_core, seedbank$treatment, sep="_") 
seedbank$stand_core_depth_treat_status <- paste(seedbank$stand_core_depth_treat, seedbank$status, sep="_") 

unique(seedbank$stand)
unique(seedbank$site)
unique(seedbank$soilcore)
unique(seedbank$depth_name)
unique(seedbank$treatment)
sort(unique(seedbank$species_diversity))
length(unique(seedbank$species_diversity)) #65 unique species
unique(seedbank$status)
unique(seedbank$stand_core_depth)
unique(seedbank$stand_core_treat) # wrap by treatment instead of ordering

```

# Total germination
```{r}
sum(seedbank$count)
```

# List species diversity
```{r}
native_seedbank <- seedbank %>% 
  filter(status == "native")
sort(unique(native_seedbank$species_diversity)) # 47 species
sort(unique(native_seedbank$family)) # 22 families

nonnative_seedbank <- seedbank %>% 
  filter(status == "nonnative")
sort(unique(nonnative_seedbank$species_diversity)) #17 species
sort(unique(nonnative_seedbank$family)) # 6 families

unknown_seedbank <- seedbank %>% 
  filter(status == "unknown")
sort(unique(unknown_seedbank$species_diversity)) # 1 species
```

# List shrub germination by hillslope
```{r}
shrub_seedbank <- seedbank %>% 
  filter(lifeform == "shrub")
sort(unique(shrub_seedbank$species_diversity)) # 10 species
sort(unique(shrub_seedbank$family)) 
length(unique(shrub_seedbank$family)) # 7 families
```

# Explore seedbank data by germination (#seeds/g sieved soil)
```{r group germination by tray}
# total number of germinates per tray
germ_tray_prep <- seedbank %>% 
  group_by(stand_core_depth_treat) %>% 
  summarize(germination_n = sum(count))

seedbank_prep <- seedbank %>% 
  group_by(stand, site, soilcore, depth_name, treatment, stand_core, stand_core_depth, stand_core_depth_treat) %>% 
  summarize(subsample_g = mean(subsample_g))

germ_tray <- germ_tray_prep %>% 
  left_join(seedbank_prep, by = "stand_core_depth_treat") %>% 
  mutate(seeds_per_g = (germination_n/subsample_g), 
         seeds_per_g_log = log(seeds_per_g))

dim(germ_tray)
# 104 rows = (7 DEG + 10 ENH + 9 INT) * 4 treatments
```

```{r explore figures}
boxplot(germ_tray$seeds_per_g)
histogram(germ_tray$seeds_per_g)
histogram(germ_tray$germination_n)

boxplot(seeds_per_g ~ stand_core, data=germ_tray, main="Seeds/g by hillslope and rep",
   xlab="Hillslope_rep", ylab="Seeds per gram")

boxplot(seeds_per_g ~ site, data=germ_tray, main="Seeds/g by hillslope and rep",
   xlab="Hillslope", ylab="Seeds per gram")

boxplot(seeds_per_g ~ subsample_g, data=germ_tray, main="Seeds/g by Subsample weight (g)",
   xlab="Subsample Weight (g)", ylab="Seeds per gram")

qplot(subsample_g, seeds_per_g, data = germ_tray)
qplot(subsample_g, seeds_per_g, data = germ_tray, facets = . ~ depth_name)
qplot(subsample_g, seeds_per_g, data = germ_tray, facets = . ~ treatment)
qplot(site, seeds_per_g, data = germ_tray, facets = . ~ depth_name)
```

```{r normality}
ggqqplot(germ_tray$seeds_per_g) 

shapiro.test(germ_tray$seeds_per_g)
# data:  germ_tray$seeds_per_g
# W = 0.62208, p-value < 2.2e-16  <-- not normally distributed

ggqqplot(germ_tray$seeds_per_g_log) 
shapiro.test(germ_tray$seeds_per_g_log)
# data:  germ_tray$seeds_per_g_log
# W = 0.98299, p-value = 0.0141 <-- closer to normal!

# poisson distribution?
plot(germ_tray(poisson.dist[]))
```

# seed/g by hillslope
```{r stats - seed/g by hillslope, include = TRUE}
kruskal.test(seeds_per_g ~ site, data = germ_tray)
# data:  seeds_per_g by site
# Kruskal-Wallis chi-squared = 64.181, df = 6, p-value = 6.338e-12 <-- sig differences

pairwise.wilcox.test(germ_tray$seeds_per_g, germ_tray$site,
                 p.adjust.method = "BH")
# 	Pairwise comparisons using Wilcoxon rank sum test with continuity correction 
# 
# data:  germ_tray$seeds_per_g and germ_tray$site 
# 
#      INT1    INT2    INT3    ENH1    ENH2    DEG1   
# INT2 0.06742 -       -       -       -       -      
# INT3 0.57288 0.53781 -       -       -       -      
# ENH1 0.09312 0.76696 0.54819 -       -       -      
# ENH2 0.69734 0.57288 0.76696 0.73886 -       -      
# DEG1 0.00021 2.7e-07 0.00024 2.7e-07 0.00117 -      
# DEG2 0.00010 3.1e-07 0.00010 3.0e-07 0.00024 0.10067

# DEG1 - INT1, INT2, INT3, ENH1, ENH2 
# DEG2 - INT1, INT2, INT3, ENH1, ENH2
# DEG1 and DEG2 are sig different from INT and ENH hillslopes. No diff between INT and ENH hillslopes.
```

# seed/g by soil depth
```{r stats - seed/g by depth, include = TRUE}
kruskal.test(seeds_per_g ~ depth_name, data = germ_tray)
# data:  seeds_per_g by depth_name
# Kruskal-Wallis chi-squared = 65.903, df = 1, p-value = 4.737e-16 <-- sig differences

pairwise.wilcox.test(germ_tray$seeds_per_g, germ_tray$depth_name,
                 p.adjust.method = "BH")
#         deep   
# surface 4.8e-16

germ_tray %>% 
  group_by(depth_name) %>% 
  summarize(total_germ = sum(germination_n))
# depth_name  total_germ
# deep	      762			
# surface	    3209	

```


# Germination by status
```{r group germination by status and tray}
germ_tray_prep_status <- seedbank %>% 
  group_by(stand_core_depth_treat_status) %>% 
  summarize(germination_n = sum(count)) %>% 
  filter(germination_n > 0)
dim(germ_tray_prep_status) # [1] 371 rows, 2 columns

seedbank_prep_status <- seedbank %>% 
  group_by(stand, site, soilcore, depth_name, status, treatment, stand_core, stand_core_depth, stand_core_depth_treat, stand_core_depth_treat_status) %>% 
  summarize(subsample_g = mean(subsample_g)) 
dim(seedbank_prep_status) # 393 rows

germ_tray_status <- germ_tray_prep_status %>% 
  left_join(seedbank_prep_status, by = "stand_core_depth_treat_status") %>% 
  mutate(seeds_per_g = (germination_n/subsample_g), 
         seeds_per_g_log = log(seeds_per_g))
dim(germ_tray_status) # 371 rows

```

```{r}
ggqqplot(germ_tray_status$seeds_per_g_log) 
ggqqplot(germ_tray_status$seeds_per_g_log) 
histogram(germ_tray_status$germination_n)


boxplot(seeds_per_g ~ status, data=germ_tray_status, main="Seeds/g by Status",
   xlab="Status", ylab="Seeds per gram")
boxplot(germination_n ~ status, data=germ_tray_status, main="Germination by Status",
   xlab="Status", ylab="Seeds per gram")

qplot(subsample_g, seeds_per_g, data = germ_tray_status, facets = . ~ status)
qplot(site, seeds_per_g, data = germ_tray_status, facets = . ~ status)
```

```{r native germination by tray}

# total number of NATIVE germinates per tray
# #
# germ_tray_prep_native <- seedbank %>% 
#   filter(status =="native") %>% 
#   group_by(stand_core_depth_treat) %>% 
#   filter(count > 0) %>% 
#   summarize(germination_n = sum(count))
# 
# seedbank_prep_native <- seedbank %>% 
#    filter(status == "native") %>% 
#    group_by(stand, site, soilcore, depth_name, treatment, stand_core, stand_core_depth, stand_core_depth_treat) %>% 
#    filter(count > 0) %>% 
#   summarize(subsample_g = mean(subsample_g))
# 
# germ_tray_native <- germ_tray_prep_native %>% 
#   left_join(seedbank_prep_native, by = "stand_core_depth_treat") %>% 
#   mutate(seeds_per_g = (germination_n/subsample_g), 
#          seeds_per_g_log = log(seeds_per_g))
# 
# summary(germ_tray_native)
# 
# germ_tray_native %>% 
#   group_by(stand_core_depth) %>% 
#   summarise(treatment = length(treatment)) # no values go over 4 so that's good
```


```{r native seed/g by depth by status, include=TRUE}
kruskal.test(seeds_per_g ~ site, data = germ_tray_native)
```

